rate: 50
controllers:
  - setpointTopic: "/control/arm/00/setpoint"
    feedbackTopic: "/control/arm/00/feedback"
    outputTopic: "/control/arm/00/output"
    P: 5 
    I: 0
    D: 0
    min: -1
    max: 1

  - setpointTopic: "/control/arm/01/setpoint"
    feedbackTopic: "/control/arm/01/feedback"
    outputTopic: "/control/arm/01/output"
    P: 5
    I: 0
    D: 0
    min: -1
    max: 1

  - setpointTopic: "/control/arm/10/setpoint"
    feedbackTopic: "/control/arm/10/feedback"
    outputTopic: "/control/arm/10/output"
    P: 5
    I: 0
    D: 0
    min: -1
    max: 1

  - setpointTopic: "/control/arm/11/setpoint"
    feedbackTopic: "/control/arm/11/feedback"
    outputTopic: "/control/arm/11/output"
    P: 5
    I: 0
    D: 0
    min: -1
    max: 1

  - setpointTopic: "/control/arm/20/setpoint"
    feedbackTopic: "/control/arm/20/feedback"
    outputTopic: "/control/arm/20/output"
    P: 5
    I: 0
    D: 0
    min: -1
    max: 1

  - setpointTopic: "/control/arm/21/setpoint"
    feedbackTopic: "/control/arm/21/feedback"
    outputTopic: "/control/arm/21/output"
    P: 5
    I: 0
    D: 0
    min: -1
    max: 1

  - setpointTopic: "/control/arm/3000/setpoint"
    feedbackTopic: "/control/arm/3000/feedback"
    outputTopic: "/control/arm/3000/output"
    P: 5
    I: 0
    D: 0
    min: -1
    max: 1
