rate: 50
controllers:
  - setpointTopic: "/control/arm/pid/turntable/setpoint"
    feedbackTopic: "/control/arm/pid/turntable/feedback"
    outputTopic: "/control/arm/pid/turntable/output"
    P: 10
    I: 0.1
    D: 0
    min: -1
    max: 1

  - setpointTopic: "/control/arm/pid/shoulder/setpoint"
    feedbackTopic: "/control/arm/pid/shoulder/feedback"
    outputTopic: "/control/arm/pid/shoulder/output"
    P: 10
    I: 0.1
    D: 0
    min: -1
    max: 1

  - setpointTopic: "/control/arm/pid/elbow/setpoint"
    feedbackTopic: "/control/arm/pid/elbow/feedback"
    outputTopic: "/control/arm/pid/elbow/output"
    P: 10
    I: 0
    D: 0
    min: -1
    max: 1

  - setpointTopic: "/control/arm/pid/forearmRoll/setpoint"
    feedbackTopic: "/control/arm/pid/forearmRoll/feedback"
    outputTopic: "/control/arm/pid/forearmRoll/output"
    P: 10
    I: 0
    D: 0
    min: -1
    max: 1

  - setpointTopic: "/control/arm/pid/wristPitch/setpoint"
    feedbackTopic: "/control/arm/pid/wristPitch/feedback"
    outputTopic: "/control/arm/pid/wristPitch/output"
    P: 10
    I: 0
    D: 0
    min: -1
    max: 1

  - setpointTopic: "/control/arm/pid/wristRoll/setpoint"
    feedbackTopic: "/control/arm/pid/wristRoll/feedback"
    outputTopic: "/control/arm/pid/wristRoll/output"
    P: 10
    I: 0
    D: 0
    min: -1
    max: 1
