arm_parameters: 
  elbow:
    encoder_parameters:
      counts_per_rotation: 1000
      offset: 500
    motor_parameters:
      gear_ratio: 1
  forearmRoll:
    encoder_parameters:
      counts_per_rotation: 1000
      offset: 500
    motor_parameters:
      gear_ratio: 1
  shoulder:
    encoder_parameters:
      counts_per_rotation: 1000
      offset: 500
    motor_parameters:
      gear_ratio: 1
  turntable:
    encoder_parameters:
      counts_per_rotation: 1000
      offset: 500
    motor_parameters:
      gear_ratio: 1
  wristPitch:
    encoder_parameters:
      counts_per_rotation: 1000
      offset: 500
    motor_parameters:
      gear_ratio: 1
  wristRoll:
    encoder_parameters:
      counts_per_rotation: 1000
      offset: 500
    motor_parameters:
      gear_ratio: 1
