arm_parameters: 
  elbow:
    encoder_parameters:
      counts_per_rotation: 1850
      offset: 675
    motor_parameters:
      gear_ratio: 3
  forearmRoll:
    encoder_parameters:
      counts_per_rotation: -1850
      offset: 576
    motor_parameters:
      gear_ratio: 3
  shoulder:
    encoder_parameters:
      counts_per_rotation: 5550
      offset: 1600
    motor_parameters:
      gear_ratio: 9
  turntable:
    encoder_parameters:
      counts_per_rotation: 6900 #7200
      offset: 90
    motor_parameters:
      gear_ratio: 3
  wristPitch:
    encoder_parameters:
      counts_per_rotation: -1850
      offset: 886
    motor_parameters:
      gear_ratio: 4.875
  wristRoll:
    encoder_parameters:
      counts_per_rotation: -1850
      offset: 981
    motor_parameters:
      gear_ratio: 4.875
