encoder_parameters: 
# elbow
  - counts_per_rotation: 1000 #-2048
    offset: 0 #610
# forearm_roll
  - counts_per_rotation: 1000 #-2048
    offset: 0 #540
# shoulder
  - counts_per_rotation: 1000 #-6144
    offset: 0 #1129
# turntable
  - counts_per_rotation: 1000 #2048
    offset: 0 #985
# wrist_pitch
  - counts_per_rotation: 1000 #2048
    offset: 0 #886
# wrist_roll
  - counts_per_rotation: 1000 #2048
    offset: 0 #1050
