encoder_parameters:
  elbow:
    counts_per_rotation: 1850
    offset: 392
  forearmRoll:
    counts_per_rotation: -1850
    offset: 956
  shoulder:
    counts_per_rotation: 5550
    offset: 1604
  turntable:
    counts_per_rotation: 6900 #7200
    offset: 90
  wristPitch:
    counts_per_rotation: -1850
    offset: 886
  wristRoll:
    counts_per_rotation: -1850
    offset: 981
