encoder_parameters: 
  elbow:
    counts_per_rotation: -2048
    offset: 610
  forearmRoll:
    counts_per_rotation: -2048
    offset: 540
  shoulder:
    counts_per_rotation: -6144
    offset: 1129
  turntable:
    counts_per_rotation: 2048
    offset: 985
  wristPitch:
    counts_per_rotation: 2048
    offset: 886
  wristRoll:
    counts_per_rotation: 2048
    offset: 1050
