encoder_parameters: 
# elbow
  - counts_per_rotation: 2048
    offset: 574
# forearm_roll
  - counts_per_rotation: -2048
    offset: 547
# shoulder
  - counts_per_rotation: 6144
    offset: 1353
# turntable
  - counts_per_rotation: 5850
    offset: 326
# wrist_pitch
  - counts_per_rotation: -2048
    offset: 864
# wrist_roll
  - counts_per_rotation: -2048
    offset: 1694
