encoder_parameters: 
# elbow
  - counts_per_rotation: -2048
    offset: 736
# forearm_roll
  - counts_per_rotation: -2048
    offset: 600
# shoulder
  - counts_per_rotation: -6144
    offset: 1450
# turntable
  - counts_per_rotation: 2048
    offset: 736
# wrist_pitch
  - counts_per_rotation: 2048
    offset: 696
# wrist_roll
  - counts_per_rotation: 2048
    offset: 1045
