arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - turntable_joint
    - shoulder_joint
    - elbowPitch_joint
    - elbowRoll_joint
    - wristPitch_joint
    - wristRoll_link
  gains:
    turntable_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbowPitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbowRoll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wristPitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wristRoll_link:
      p: 100
      d: 1
      i: 1
      i_clamp: 1