controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - turntable_joint
      - shoulder_joint
      - elbowPitch_joint
      - elbowRoll_joint
      - wristPitch_joint
      - wristRoll_link