controller_list:
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - turntable
      - shoulder
      - elbow
      - forearm_roll
      - wrist_pitch
      - wrist_roll
initial:  # Define initial robot poses.
#  - group: arm
#    pose: home

  []