controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - turntable
      - shoulder
      - elbow
      - forearm_roll
      - wrist_pitch
      - wrist_roll
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - turntable
      - shoulder
      - elbow
      - forearm_roll
      - wrist_pitch
      - wrist_roll